FROM mcr.microsoft.com/devcontainers/python:2-3.13-trixie

RUN apt update && apt upgrade -y && apt install -y gdal-bin libgdal-dev direnv nodejs npm git make && \
    apt clean && \
    rm -rf /var/lib/apt/lists/* && \
    pip install --no-cache-dir --upgrade pip

RUN git clone https://github.com/mapbox/tippecanoe.git && cd tippecanoe &&  make -j && make install

COPY direnv.toml /home/vscode/.config/direnv/
COPY .bashrc /home/vscode/
